### ISSUE TITLE
Updating session is not workin on login resolver

### ISSUE THREAD

**Issue by Husamui** [benawad/graphql-ts-server-boilerplate#3]
**steps to reproduce**

- register new account
- confirm email
- login with that email/password

query "me" 

**Actual:** 
returning null 

**expected:**
returning the logged in user

**Comment by benawad** [comment]
What branch?

**Comment by Husamui** [comment]
on 27_twitter_oauth

**Comment by benawad** [comment]
Is this when you run the test, or try out the server yourself?

**Comment by Husamui** [comment]
I'm trying the server myself

**Comment by Husamui** [comment]
I did hardcoded "http://localhost:4000/" in the cors origin

**Comment by Husamui** [comment]
You right, Thank you @benawad Problem solved, it was with Graphql playground settings
