### ISSUE TITLE
 Graphql schema files not copied over to dist.

### ISSUE THREAD

**Issue by immortalx** [benawad/graphql-ts-server-boilerplate#5]
Hey Ben!

When we compile to javascript the schema.graphql is not copied over to the dist folder so genSchema() doesn't work. 

I'm not sure if it's intended to work only with ts-node.

By the way, thanks for this nice series!

**Comment by benawad** [comment]
I forgot to address this, there's a package called [copyfiles](https://github.com/calvinmetcalf/copyfiles) that you can add to the build command to copy them over. Here's what your build command can looks like:

```
rm -rf dist && tsc && copyfiles -u 1 src/**/*.graphql dist/
```

**Comment by immortalx** [comment]
That works really well, thank you very much!
